apiVersion: apps/v1
kind: Deployment
metadata:
  name: atualizacao-deployment
  labels:
    app: atualizacao
  annotations:
    owner: "EquipeBackend"
    description: "Microsservico que recebe requisicoes de atualizacao de contatos e publica eventos na fila."
    last-updated: "2025-07-31T21:52:00-03:00"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: atualizacao
  template:
    metadata:
      labels:
        app: atualizacao
    spec:
      containers:
      - name: atualizacao-container
        image: microservices-atualizacao:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
        env:
        - name: ConnectionStrings__RabbitMQ
          valueFrom:
            configMapKeyRef:
              name: app-configmap
              key: RabbitMQ__Host