apiVersion: v1
kind: Service
metadata:
  name: atualizacao-service
  annotations:
    description: "Expõe o servico de atualizacao (atualizacao-deployment) dentro do cluster."
    prometheus.io/scrape: 'true'
    prometheus.io/path:   '/metrics'
    prometheus.io/port:   '80'
spec:
  type: NodePort
  selector:
    app: atualizacao
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30002 # Porta de acesso externa