apiVersion: v1
kind: Service
metadata:
  name: sqlserver-service
spec:
  type: NodePort
  ports:
  - port: 1433
    targetPort: 1433
    nodePort: 31433 # Opcional: definir uma porta fixa
  selector:
    app: sqlserver