apiVersion: v1
kind: Service
metadata:
  name: cadastro-service
  annotations:
    description: "Expõe o servico de cadastro (cadastro-deployment) dentro do cluster."
    prometheus.io/scrape: 'true'
    prometheus.io/path: '/metrics'
    prometheus.io/port: '80'
spec:
  type: NodePort
  selector:
    app: cadastro
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30001 # Porta de acesso externa