apiVersion: apps/v1
kind: Deployment
metadata:
  name: exclusao-deployment
  labels:
    app: exclusao
  annotations:
    owner: "EquipeBackend"
    description: "Microsservico que recebe requisicoes de exclusao de contatos e publica eventos na fila."
    last-updated: "2025-07-31T21:52:00-03:00"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: exclusao
  template:
    metadata:
      labels:
        app: exclusao
    spec:
      containers:
      - name: exclusao-container
        image: microservices-exclusao:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
        env:
        - name: ConnectionStrings__RabbitMQ
          valueFrom:
            configMapKeyRef:
              name: app-configmap
              key: RabbitMQ__Host