apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
type: Opaque
stringData:
  SA_PASSWORD: "1a2b3c4d"
  SqlServer__ConnectionString: "Server=sqlserver-service,1433;Database=ContactDb;User Id=sa;Password=1a2b3c4d;TrustServerCertificate=True;"