apiVersion: v1
kind: Service
metadata:
  name: persistencia-service
  annotations:
    description: "Expõe o servico de persistencia (persistencia-deployment) para scraping de metricas pelo Prometheus."
    prometheus.io/scrape: 'true'
    prometheus.io/path:   '/metrics'
    prometheus.io/port:   '8081'
spec:
  type: ClusterIP
  selector:
    app: persistencia
  ports:
  - protocol: TCP
    port: 8081
    targetPort: 8081