apiVersion: v1
kind: Service
metadata:
  name: consulta-service
  annotations:
    description: "Expõe o servico de consulta (consulta-deployment) dentro do cluster."
    prometheus.io/scrape: 'true'
    prometheus.io/path:   '/metrics'
    prometheus.io/port:   '80'
spec:
  type: NodePort
  selector:
    app: consulta
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30004 # Porta de acesso externa